version: '3'

services:
  code-server:
    image: dockerhub.qingcloud.com/openos365/openos365-10027-ubuntu-22-04-lts-docker-main-root:latest
    ports:
      - "18080:18080"
    volumes:
      - ~/git/:/root/git/
      - ~/.ssh/:/root/.ssh/
    environment:
      - dev_version=openos365
    command: code-server.start